commit_message: '[Localization] Update %language% translations'
append_commit_message: false
files:
  - source: /Zebra/Resources/en.lproj/*.strings
    translation: /Zebra/Resources/%osx_code%/*.strings
